// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWC51J1fKxIe2EBSQWrf-6OPloAN0BoE',
    appId: '1:708163218868:web:d641ff5163154903b396e1',
    messagingSenderId: '708163218868',
    projectId: 'class-sync-timetable-manager',
    authDomain: 'class-sync-timetable-manager.firebaseapp.com',
    storageBucket: 'class-sync-timetable-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KtKYqy2zaR0H-2Ww25n_QtgnC8RKxg0',
    appId: '1:708163218868:android:76c0f8e7ffe110fcb396e1',
    messagingSenderId: '708163218868',
    projectId: 'class-sync-timetable-manager',
    storageBucket: 'class-sync-timetable-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMljK-xDLr0nXv9a1YvnnR1vkrom1MUk',
    appId: '1:708163218868:ios:84b3561cbcd8e28eb396e1',
    messagingSenderId: '708163218868',
    projectId: 'class-sync-timetable-manager',
    storageBucket: 'class-sync-timetable-manager.appspot.com',
    iosBundleId: 'com.example.classSyncTimetableManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMljK-xDLr0nXv9a1YvnnR1vkrom1MUk',
    appId: '1:708163218868:ios:df41bf37fd90a52fb396e1',
    messagingSenderId: '708163218868',
    projectId: 'class-sync-timetable-manager',
    storageBucket: 'class-sync-timetable-manager.appspot.com',
    iosBundleId: 'com.example.classSyncTimetableManager.RunnerTests',
  );
}
